Analysis
EnergyAnalysis Model
Demonstrates how to use EnergyAnalysisModel API.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\GeometryAPI\EnergyAnalysisModel\CS\bin\Debug\EnergyAnalysisModel.dll
Ara3D.RevitSampleBrowser.EnergyAnalysisModel.CS.Command

Annotation
Tag Rooms
Auto tag all rooms in a specified level.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\AutoTagRooms\CS\bin\Debug\AutoTagRooms.dll
Ara3D.RevitSampleBrowser.AutoTagRooms.CS.Command

Annotation
ColorFill Scheme and Legend creation and modification.
This sample demonstrates how to create ColorFill scheme, add entries and modify entries for colorFill scheme. It also demonstrates how to create colorFill legend with scheme and modify its appearance.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ColorFill\CS\bin\Debug\ColorFill.dll
Ara3D.RevitSampleBrowser.ColorFill.CS.Command

Annotation
Create Dimensions
Add a dimension to a selected structural wall from its start to its end. Name the dimensions 'Dimension N' where N is an increasing number for each dimension.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateDimensions\CS\bin\Debug\CreateDimensions.dll
Ara3D.RevitSampleBrowser.CreateDimensions.CS.Command

Annotation
LeaderLineAndDimensionLineSuperposition.
Using new dimension api to move leader end point. Make the dimension line and leader line to be superposition. 
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DimensionLeaderEnd\CS\bin\Debug\DimensionLeaderEnd.dll
Ara3D.RevitSampleBrowser.DimensionLeaderEnd.CS.MoveHorizontally

Annotation
MoveToPickedPoint.
Using new dimension api to move leader end point. Move to picked point. 
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DimensionLeaderEnd\CS\bin\Debug\DimensionLeaderEnd.dll
Ara3D.RevitSampleBrowser.DimensionLeaderEnd.CS.MoveToPickedPoint

Annotation
Spot Dimension
Get all spot dimensions in all views and show their properties.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SpotDimension\CS\bin\Debug\SpotDimension.dll
Ara3D.RevitSampleBrowser.SpotDimension.CS.Command

Annotation
TagBeam - Tag Beam
Tag beam's start and end.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\TagBeam\CS\bin\Debug\TagBeam.dll
Ara3D.RevitSampleBrowser.TagBeam.CS.Command

Annotation
TagBeam - Tag Rebar
Tag selected Rebar.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\TagBeam\CS\bin\Debug\TagBeam.dll
Ara3D.RevitSampleBrowser.TagBeam.CS.TagRebar

Annotation
TagBeam - Create Text
Create a new TextNote instance for selected Rebar.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\TagBeam\CS\bin\Debug\TagBeam.dll
Ara3D.RevitSampleBrowser.TagBeam.CS.CreateText

Annotation, Basics
Capitalize all TextNote elements
This command iterates through the document and applies the 'AllCaps' formatting to them.  This will show text in upper case characters.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CapitalizeAllTextNotes\CS\bin\Debug\CapitalizeAllTextNotes.dll
Ara3D.RevitSampleBrowser.CapitalizeAllTextNotes.CS.Command

Annotation, Basics
Delete Dimensions
Delete all unpinned dimensions found in current selection.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DeleteDimensions\CS\bin\Debug\DeleteDimensions.dll
Ara3D.RevitSampleBrowser.DeleteDimensions.CS.Command

Annotation, Basics
In-Canvas controls
This sample will demonstrate how to create, keep track of and handle clicks on In-Canvas controls.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\InCanvasControlAPI\CS\bin\Debug\InCanvasControlAPI.dll
Ara3D.RevitSampleBrowser.InCanvasControlAPI.CS.Command

Annotation, Elements
Infrastructure Alignment Station Label
Demonstrates the use of API for finding and labeling an infrastructure alignment element.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CivilAlignments\CS\bin\Debug\CivilAlignments.dll
Ara3D.RevitSampleBrowser.CivilAlignments.CS.CreateAlignmentStationLabelsCmd

Annotation, Elements
Infrastructure Alignment Properties
Demonstrates the use of API for listing properties of an infrastructure alignment element and its labels.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CivilAlignments\CS\bin\Debug\CivilAlignments.dll
Ara3D.RevitSampleBrowser.CivilAlignments.CS.ShowPropertiesCmd

Annotation, Elements, Views
Create PathOfTravel.
This sample demonstrated how to create PathOfTravel elements from room(s) to door(s) in a plan view.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PathOfTravel\CS\bin\Debug\PathOfTravel.dll
Ara3D.RevitSampleBrowser.PathOfTravelCreation.CS.Command

Basics
Delete Objects (CS)
Delete selected elements.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DeleteObject\CS\bin\Debug\DeleteObject.dll
Ara3D.RevitSampleBrowser.DeleteObject.CS.Command

Basics
ErrorHandling
Demonstrates how to use the error handling framework..
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ErrorHandling\CS\bin\Debug\ErrorHandling.dll
Ara3D.RevitSampleBrowser.ErrorHandling.CS.Command

Basics
ProgressNotifier
ProgressNotifier
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Events\ProgressNotifier\CS\bin\Debug\ProgressNotifier.dll
Ara3D.RevitSampleBrowser.ProgressNotifier.CS.Command

Basics
Hello Revit (CS)
Shows how a basic ExternalCommand can be added to the Revit user interface.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\HelloRevit\CS\bin\Debug\HelloRevit.dll
Ara3D.RevitSampleBrowser.HelloRevit.CS.Command

Basics
Journaling
Show how an external application can participate in the journaling mechanism.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Journaling\CS\bin\Debug\Journaling.dll
Ara3D.RevitSampleBrowser.Journaling.CS.Command

Basics
Show Modeless Form (External Event)
This sample shows how to utilize an External Event object  in order to communicate with the Revit API from an external  modeless dialog.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ModelessDialog\ModelessForm_ExternalEvent\CS\bin\Debug\ModelessForm_ExternalEvent.dll
Ara3D.RevitSampleBrowser.ModelessForm_ExternalEvent.CS.Command

Basics
Show Modeless Form (Idling Event)
An applicaiton with a modeless dialog using the Idling event to comunicate with Revit API
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ModelessDialog\ModelessForm_IdlingEvent\CS\bin\Debug\ModelessForm_IdlingEvent.dll
Ara3D.RevitSampleBrowser.ModelessForm_IdlingEvent.CS.Command

Basics
Analyze Wall Face
This sample shows how to utilize the Applicaiton.Idling event in order to communicate with the Revit API from an external work thread.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\MultiThreading\WorkThread\CS\bin\Debug\WorkThread.dll
Ara3D.RevitSampleBrowser.WorkThread.CS.Command

Basics
Highlight by Phase
Highlight by Phase.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PhaseSample\VB.NET\bin\PhaseSample.dll
Ara3D.RevitSampleBrowser.PhaseSample.VB.NET.Command

Basics
Project Information
Project Information.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ProjectInfo\CS\bin\Debug\ProjectInfo.dll
Ara3D.RevitSampleBrowser.ProjectInfo.CS.Command

Basics
TransactionControl
Demonstrate how to use transaction control.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\TransactionControl\CS\bin\Debug\TransactionControl.dll
Ara3D.RevitSampleBrowser.TransactionControl.CS.Command

Basics, Data Exchange
Units API
The sample of Revit Units API.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Units\CS\bin\Debug\Units.dll
Ara3D.RevitSampleBrowser.Units.CS.Command

Basics, Elements
Display Options
Display Options.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DesignOptionReader\VB.NET\bin\DesignOptionReader.dll
Ara3D.RevitSampleBrowser.DesignOptionReader.VB.NET.Command

Basics, Families
Interactive placement of family instance via options
This sample demonstrates how to place the family instance via options
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PlacementOptions\CS\bin\Debug\PlacementOptions.dll
Ara3D.RevitSampleBrowser.PlacementOptions.CS.Command

Basics, Families
RvtCmd_LibraryPaths
List the Revit library paths.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RevitCommands\VB.NET\bin\RevitCommands.dll
Ara3D.RevitSampleBrowser.RevitCommands.VB.NET.RvtCmd_LibraryPaths

Basics, Families
RvtCmd_LoadFamilySymbol
Load a family symbol/type.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RevitCommands\VB.NET\bin\RevitCommands.dll
Ara3D.RevitSampleBrowser.RevitCommands.VB.NET.RvtCmd_LoadFamilySymbol

Basics, Families
RvtCmd_LoadFamily
Load a family.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RevitCommands\VB.NET\bin\RevitCommands.dll
Ara3D.RevitSampleBrowser.RevitCommands.VB.NET.RvtCmd_LoadFamily

Basics, Families
RvtCmd_Selection
show how to use selection set.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RevitCommands\VB.NET\bin\RevitCommands.dll
Ara3D.RevitSampleBrowser.RevitCommands.VB.NET.RvtCmd_Selection

Basics, Families
RvtCmd_ShowElementData
show parameters in selected entities.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RevitCommands\VB.NET\bin\RevitCommands.dll
Ara3D.RevitSampleBrowser.RevitCommands.VB.NET.RvtCmd_ShowElementData

Basics
Display graphics using DirectContext3D
Select elements whose graphics should be redrawn using DirectContext3D.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DuplicateGraphics\CS\bin\Debug\DuplicateGraphics.dll
Ara3D.RevitSampleBrowser.DuplicateGraphics.CS.CommandDuplicateGraphics

Basics
Clear DirectContext3D graphics
Remove external graphics.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DuplicateGraphics\CS\bin\Debug\DuplicateGraphics.dll
Ara3D.RevitSampleBrowser.DuplicateGraphics.CS.CommandClearExternalGraphics

Basics
ReferencePlane
Allow user to create a reference plane at the left face of the wall or at the bottom of slab which is selected first.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ReferencePlane\CS\bin\Debug\ReferencePlane.dll
Ara3D.RevitSampleBrowser.ReferencePlane.CS.Command

Basics, Views
Export 2D views with CustomExporter
Export 2D views with CustomExporter, using varying options of the exporter.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CustomExporter\Custom2DExporter\CS\bin\Debug\Custom2DExporter.dll
Ara3D.RevitSampleBrowser.Custom2DExporter.CS.Command

Basics, Parameters
About Revit
Show the Revit product name, version and build number.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\VersionChecking\CS\bin\Debug\VersionChecking.dll
Ara3D.RevitSampleBrowser.VersionChecking.CS.Command

Basics, Structure
Rotate Framing Objects (CS)
Rotate selected objects, such as beams, braces and columns.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RotateFramingObjects\CS\bin\Debug\RotateFramingObjects.dll
Ara3D.RevitSampleBrowser.RotateFramingObjects.CS.RotateFramingObjects

Data Exchange
Arch Sample - Export to Excel
Export data to Excel, sorted by categories
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ArchSample\VB.NET\bin\ArchSample.dll
Ara3D.RevitSampleBrowser.ArchSample.VB.NET.Command

Data Exchange
Import and Export
Export current project to dwg, dwf(x), gbxml or fbx files and import a dwg or image file into Revit.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ImportExport\CS\bin\Debug\ImportExport.dll
Ara3D.RevitSampleBrowser.ImportExport.CS.Command

Data Exchange
Panel Schedule Sample - Export Data
Exoport Revit Panle Schedule(s) to CSV file(s) or HTML page(s).
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PanelSchedule\CS\bin\Debug\PanelSchedule.dll
Ara3D.RevitSampleBrowser.PanelSchedule.CS.PanelScheduleExport

Data Exchange
Panel Schedule Sample - View Instance Creation
Create Panel Schedule View instance for a panel.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PanelSchedule\CS\bin\Debug\PanelSchedule.dll
Ara3D.RevitSampleBrowser.PanelSchedule.CS.InstanceViewCreation

Data Exchange
Panel Schedule Sample - Sheet Instance Creation
Place Panel Schedule View instance on a sheet view.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PanelSchedule\CS\bin\Debug\PanelSchedule.dll
Ara3D.RevitSampleBrowser.PanelSchedule.CS.SheetImport

Data Exchange
View Printer
Print user selected printable views.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ViewPrinter\CS\bin\Debug\ViewPrinter.dll
Ara3D.RevitSampleBrowser.ViewPrinter.CS.Command

Data Exchange, Families
DWGFamilyCreation
Import dwg file into family document.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FamilyCreation\DWGFamilyCreation\CS\bin\Debug\DWGFamilyCreation.dll
Ara3D.RevitSampleBrowser.DWGFamilyCreation.CS.Command

Elements
Create CompoundStructure for wall
This command is to create CompoundStructure for wall.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CompoundStructure\CS\bin\Debug\CompoundStructure.dll
Ara3D.RevitSampleBrowser.CompoundStructureCreation.CS.WallCompoundStructure

Elements
Create and set FillPattern
Create and set FillPattern or LinePattern to face and grid
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateFillPattern\CS\bin\Debug\CreateFillPattern.dll
Ara3D.RevitSampleBrowser.CreateFillPattern.CS.Command

Elements
Curtain System
Create curtain systems and edit their curtain grids
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CurtainSystem\CS\bin\Debug\CurtainSystem.dll
Ara3D.RevitSampleBrowser.CurtainSystem.CS.Command

Elements
Curtain Wall and Grid
Create a curtain wall and edit its grid
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CurtainWallGrid\CS\bin\Debug\CurtainWallGrid.dll
Ara3D.RevitSampleBrowser.CurtainWallGrid.CS.Command

Elements
Datum Alignment
Datumplane modification
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DatumsModification\CS\bin\Debug\DatumsModification.dll
Ara3D.RevitSampleBrowser.DatumsModification.CS.DatumAlignment

Elements
Datum Propagation
Datumplane modification
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DatumsModification\CS\bin\Debug\DatumsModification.dll
Ara3D.RevitSampleBrowser.DatumsModification.CS.DatumPropagation

Elements
Datum Style Modification
Datumplane modification
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DatumsModification\CS\bin\Debug\DatumsModification.dll
Ara3D.RevitSampleBrowser.DatumsModification.CS.DatumStyleModification

Elements
Create and modify view filters.
Create and modify view filters.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ElementFilter\ViewFilters\CS\bin\Debug\ViewFilters.dll
Ara3D.RevitSampleBrowser.ViewFilters.CS.Command

Elements
Extensible Storage Manager
Extensible Storage Manager
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ExtensibleStorageManager\ExtensibleStorageManager\CS\bin\Debug\ExtensibleStorageManager.dll
ExtensibleStorageManager.Command

Elements
ExtensibleStorageUtility-DeleteStorage
ExtensibleStorageUtility-DeleteStorage
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ExtensibleStorageUtility\CS\bin\Debug\ExtensibleStorageUtility.dll
Ara3D.RevitSampleBrowser.ExtensibleStorageUtility.CS.DeleteStorage

Elements
ExtensibleStorageUtility-QueryStorage
ExtensibleStorageUtility-QueryStorage
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ExtensibleStorageUtility\CS\bin\Debug\ExtensibleStorageUtility.dll
Ara3D.RevitSampleBrowser.ExtensibleStorageUtility.CS.QueryStorage

Elements
Foundation Slab
Convert regular floors at the base of the building to octagonal slabs.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FoundationSlab\CS\bin\Debug\FoundationSlab.dll
Ara3D.RevitSampleBrowser.FoundationSlab.CS.Command

Elements
GenerateFloor
Generate a floor using a selection of walls that make a closed outline.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\GenerateFloor\CS\bin\Debug\GenerateFloor.dll
Ara3D.RevitSampleBrowser.GenerateFloor.CS.Command

Elements
Grid Creation
Show how to create grids.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\GridCreation\CS\bin\Debug\GridCreation.dll
Ara3D.RevitSampleBrowser.GridCreation.CS.Command

Elements
Create levels
Show how to get all the levels in a document and how to create and delete a level and set its properties.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\LevelsProperty\CS\bin\Debug\LevelsProperty.dll
Ara3D.RevitSampleBrowser.LevelsProperty.CS.Command

Elements
Model Lines
Report the number of each model line type and allow the user to specify the shape and sketch plane to create some new model lines.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ModelLines\CS\bin\Debug\ModelLines.dll
Ara3D.RevitSampleBrowser.ModelLines.CS.Command

Elements
New hosted sweep
Create hosted sweep and modify created hosted sweep
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\NewHostedSweep\CS\bin\Debug\NewHostedSweep.dll
Ara3D.RevitSampleBrowser.NewHostedSweep.CS.Command

Elements
New Openings
Create openings on the selected floor or wall.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\NewOpenings\CS\bin\Debug\NewOpenings.dll
Ara3D.RevitSampleBrowser.NewOpenings.CS.Command

Elements
NewRoof
Create or edit footprint roof and extrusion roof.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\NewRoof\CS\bin\Debug\NewRoof.dll
Ara3D.RevitSampleBrowser.NewRoof.CS.Command

Elements
Openings
Display openings in project, and create model lines along its edges.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Openings\CS\bin\Debug\Openings.dll
Ara3D.RevitSampleBrowser.Openings.CS.Command

Elements
PerformanceAdviserControl
PerformanceAdviserControl
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PerformanceAdviserControl\CS\bin\Debug\PerformanceAdviserControl.dll
Ara3D.RevitSampleBrowser.PerformanceAdviserControl.CS.UICommand

Elements
Shared Coordinate System
Display the locations and site information of the project.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SharedCoordinateSystem\CS\bin\Debug\SharedCoordinateSystem.dll
Ara3D.RevitSampleBrowser.SharedCoordinateSystem.CS.Command

Elements
Stairs automation
A utility sample that creates a series of stairs, stairs runs and stairs landings configurations based upon predefined rules and parameters.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\StairsAutomation\CS\bin\Debug\StairsAutomation.dll
Ara3D.RevitSampleBrowser.StairsAutomation.CS.Command

Toposolid
Toposolid ContourSettingCreation
API samples for toposolid related features.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Toposolid\CS\bin\Debug\Toposolid.dll
Ara3D.RevitSampleBrowser.Toposolid.CS.ContourSettingCreation

Toposolid
Toposolid ContourSettingModification
API samples for toposolid related features.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Toposolid\CS\bin\Debug\Toposolid.dll
Ara3D.RevitSampleBrowser.Toposolid.CS.ContourSettingModification

Toposolid
Toposolid SSEPointVisibility
API samples for toposolid related features.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Toposolid\CS\bin\Debug\Toposolid.dll
Ara3D.RevitSampleBrowser.Toposolid.CS.SSEPointVisibility

Toposolid
Toposolid SimplifyToposolid
API samples for toposolid related features.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Toposolid\CS\bin\Debug\Toposolid.dll
Ara3D.RevitSampleBrowser.Toposolid.CS.SimplifyToposolid

Toposolid
Toposolid SplitToposolid
API samples for toposolid related features.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Toposolid\CS\bin\Debug\Toposolid.dll
Ara3D.RevitSampleBrowser.Toposolid.CS.SplitToposolid

Toposolid
Toposolid ToposolidCreation
API samples for toposolid related features.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Toposolid\CS\bin\Debug\Toposolid.dll
Ara3D.RevitSampleBrowser.Toposolid.CS.ToposolidCreation

Toposolid
Toposolid ToposolidFromDWG
API samples for toposolid related features.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Toposolid\CS\bin\Debug\Toposolid.dll
Ara3D.RevitSampleBrowser.Toposolid.CS.ToposolidFromDWG

Toposolid
Toposolid ToposolidFromSurface
API samples for toposolid related features.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Toposolid\CS\bin\Debug\Toposolid.dll
Ara3D.RevitSampleBrowser.Toposolid.CS.ToposolidFromSurface


Elements
Winder Stairs
API Sketched Winder Stairs
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\WinderStairs\CS\bin\Debug\WinderStairs.dll
Ara3D.RevitSampleBrowser.WinderStairs.CS.Command

Elements
Shaft Hole Puncher
Create shaft opening or create opening on wall, floor or beam.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ShaftHolePuncher\CS\bin\Debug\ShaftHolePuncher.dll
Ara3D.RevitSampleBrowser.ShaftHolePuncher.CS.Command

Elements
SlabShapeEditing
Create vertex and crease on slab to edit it's shape.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SlabShapeEditing\CS\bin\Debug\SlabShapeEditing.dll
Ara3D.RevitSampleBrowser.SlabShapeEditing.CS.Command

Analytical Model
Analytical Model: AddAssociation
ContextualAnalyticalModel.AddAssociation
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.AddAssociation

Analytical Model
Analytical Model: AddCustomAssociation
ContextualAnalyticalModel.AddCustomAssociation
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.AddCustomAssociation

Analytical Model
Analytical Model: AnalyticalNodeConnStatus
ContextualAnalyticalModel.AnalyticalNodeConnStatus
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.AnalyticalNodeConnStatus

Analytical Model
Analytical Model: CreateAnalyticalPanel
ContextualAnalyticalModel.CreateAnalyticalPanel
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.CreateAnalyticalPanel

Analytical Model
Analytical Model: CreateAnalyticalCurvedPanel
ContextualAnalyticalModel.CreateAnalyticalCurvedPanel
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.CreateAnalyticalCurvedPanel

Analytical Model
Analytical Model: CreateAnalyticalMember
ContextualAnalyticalModel.CreateAnalyticalMember
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.CreateAnalyticalMember

Analytical Model
Analytical Model: CreateAreaLoadWithRefPoint
ContextualAnalyticalModel.CreateAreaLoadWithRefPoint
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.CreateAreaLoadWithRefPoint

Analytical Model
Analytical Model: CreateCustomAreaLoad
ContextualAnalyticalModel.CreateCustomAreaLoad
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.CreateCustomAreaLoad

Analytical Model
Analytical Model: CreateCustomLineLoad
ContextualAnalyticalModel.CreateCustomLineLoad
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.CreateCustomLineLoad

Analytical Model
Analytical Model: CreateCustomPointLoad
ContextualAnalyticalModel.CreateCustomPointLoad
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.CreateCustomPointLoad

Analytical Model
Analytical Model: FlipAnalyticalMember
ContextualAnalyticalModel.FlipAnalyticalMember
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.FlipAnalyticalMember

Analytical Model
Analytical Model: MemberForcesAnalyticalMember
ContextualAnalyticalModel.MemberForcesAnalyticalMember
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.MemberForcesAnalyticalMember

Analytical Model
Analytical Model: ModifyPanelContour
ContextualAnalyticalModel.ModifyPanelContour
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.ModifyPanelContour

Analytical Model
Analytical Model: MoveAnalyticalMemberUsingElementTransformUtils
ContextualAnalyticalModel.MoveAnalyticalMemberUsingElementTransformUtils
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.MoveAnalyticalMemberUsingElementTransformUtils

Analytical Model
Analytical Model: MoveAnalyticalMemberUsingSetCurve
ContextualAnalyticalModel.MoveAnalyticalMemberUsingSetCurve
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.MoveAnalyticalMemberUsingSetCurve

Analytical Model
Analytical Model: MoveAnalyticalNodeUsingElementTransformUtils
ContextualAnalyticalModel.MoveAnalyticalNodeUsingElementTransformUtils
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.MoveAnalyticalNodeUsingElementTransformUtils

Analytical Model
Analytical Model: MoveAnalyticalPanelUsingElementTransformUtils
ContextualAnalyticalModel.MoveAnalyticalPanelUsingElementTransformUtils
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.MoveAnalyticalPanelUsingElementTransformUtils

Analytical Model
Analytical Model: MoveAnalyticalPanelUsingSketchEditScope
ContextualAnalyticalModel.MoveAnalyticalPanelUsingSketchEditScope
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.MoveAnalyticalPanelUsingSketchEditScope

Analytical Model
Analytical Model: ReleaseConditionsAnalyticalMember
ContextualAnalyticalModel.ReleaseConditionsAnalyticalMember
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.ReleaseConditionsAnalyticalMember

Analytical Model
Analytical Model: RemoveAssociation
ContextualAnalyticalModel.RemoveAssociation
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.RemoveAssociation

Analytical Model
Analytical Model: SetOuterContourForPanels
ContextualAnalyticalModel.SetOuterContourForPanels
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.SetOuterContourForPanels





Elements, Parameters
Move Linear
Move a linear element, such as a structural beam.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\MoveLinear\CS\bin\Debug\MoveLinear.dll
Ara3D.RevitSampleBrowser.MoveLinear.CS.Command

Elements, Parameters
Slab Properties (CS)
Display slab properties.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SlabProperties\CS\bin\Debug\SlabProperties.dll
Ara3D.RevitSampleBrowser.SlabProperties.CS.Command

Elements, Parameters
Span Direction
Display slab properties (span direction and span direction symbols).
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SpanDirection\CS\bin\Debug\SpanDirection.dll
Ara3D.RevitSampleBrowser.SpanDirection.CS.Command

Families
Create Air Handler
Create one air handler and add connectors.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FamilyCreation\CreateAirHandler\CS\bin\Debug\CreateAirHandler.dll
Ara3D.RevitSampleBrowser.CreateAirHandler.CS.Command

Families
Create Truss
Create truss in truss family document.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FamilyCreation\CreateTruss\CS\bin\Debug\CreateTruss.dll
Ara3D.RevitSampleBrowser.CreateTruss.CS.Command

Families
GenericModelCreation
The sample show how to create Generic Model family at family document.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FamilyCreation\GenericModelCreation\CS\bin\Debug\GenericModelCreation.dll
Ara3D.RevitSampleBrowser.GenericModelCreation.CS.Command

Families
TypeRegeneration
The command check every type regeneration without any error
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FamilyCreation\TypeRegeneration\CS\bin\Debug\TypeRegeneration.dll
Ara3D.RevitSampleBrowser.TypeRegeneration.CS.Command

Families
ValidateParameters
This command will validate if every type has valid values for certain parameter
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FamilyCreation\ValidateParameters\CS\bin\Debug\ValidateParameters.dll
Ara3D.RevitSampleBrowser.ValidateParameters.CS.Command

Families
WindowWizard
This command is to create window family via wizard
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FamilyCreation\WindowWizard\CS\bin\Debug\WindowWizard.dll
Ara3D.RevitSampleBrowser.WindowWizard.CS.Command

Families
In-Place Members
Display In-Place Member's Properties and AnalyticalModel.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\InPlaceMembers\CS\bin\Debug\InPlaceMembers.dll
Ara3D.RevitSampleBrowser.InPlaceMembers.CS.Command

Families
DividedSurface by intersects
Customize DividedSurface with intersection elements
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\DividedSurfaceByIntersects\CS\bin\Debug\DividedSurfaceByIntersects.dll
Ara3D.RevitSampleBrowser.DividedSurfaceByIntersects.CS.Command

Families
New Extrusion Form
The sample show how to create extrusion form at family document.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\NewForm\CS\bin\Debug\NewForm.dll
Ara3D.RevitSampleBrowser.NewForm.CS.MakeExtrusionForm

Families
New Revolve Form
The sample show how to create revolve form at family document.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\NewForm\CS\bin\Debug\NewForm.dll
Ara3D.RevitSampleBrowser.NewForm.CS.MakeRevolveForm

Families
New Loft Form
The sample show how to create loft form at family document.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\NewForm\CS\bin\Debug\NewForm.dll
Ara3D.RevitSampleBrowser.NewForm.CS.MakeLoftForm

Families
New Swept Blend Form
The sample show how to create swept blend form at family document.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\NewForm\CS\bin\Debug\NewForm.dll
Ara3D.RevitSampleBrowser.NewForm.CS.MakeSweptBlendForm

Families
New Cap Form
The sample show how to create cap form at family document.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\NewForm\CS\bin\Debug\NewForm.dll
Ara3D.RevitSampleBrowser.NewForm.CS.MakeCapForm

Families
Place FamilyInstance by face
Create family instance on face.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PlaceFamilyInstanceByFace\CS\bin\Debug\PlaceFamilyInstanceByFace.dll
Ara3D.RevitSampleBrowser.PlaceFamilyInstanceByFace.CS.Command

Families
Type Selector
Retrieve all the types of the selected element, such as a wall and allow the selected element's type to be changed.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\TypeSelector\VB.NET\bin\TypeSelector.dll
Ara3D.RevitSampleBrowser.TypeSelector.VB.NET.Command

Families, MEP
Create Ductwork Stiffener
Create Ductwork Stiffener
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateDuctworkStiffener\CS\bin\Debug\CreateDuctworkStiffener.dll
Ara3D.RevitSampleBrowser.CreateDuctworkStiffener.CS.Command

Families, Parameters
AddParameterToFamily
Sample to show how to automatically add a large set of parameters to a family.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FamilyCreation\AutoParameter\CS\bin\Debug\AutoParameter.dll
Ara3D.RevitSampleBrowser.AutoParameter.CS.AddParameterToFamily

Families, Parameters
AddParameterToFamilies
Sample to show how to automatically add a large set of parameters to multiple family files.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FamilyCreation\AutoParameter\CS\bin\Debug\AutoParameter.dll
Ara3D.RevitSampleBrowser.AutoParameter.CS.AddParameterToFamilies

Families, Parameters
Command
Command
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FamilyParametersOrder\CS\bin\Debug\FamilyParametersOrder.dll
Ara3D.RevitSampleBrowser.FamilyParametersOrder.CS.Command

Geometry
Multithreaded Calculation
Multithreaded Calculation
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\AnalysisVisualizationFramework\MultithreadedCalculation\CS\bin\Debug\MultithreadedCalculation.dll
Ara3D.RevitSampleBrowser.MultithreadedCalculation.CS.MultithreadedCalculation

Geometry
Gradient Results On Surface
Gradient Results On Surface
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\AnalysisVisualizationFramework\SpatialFieldGradient\CS\bin\Debug\SpatialFieldGradient.dll
Ara3D.RevitSampleBrowser.AnalysisVisualizationFramework.CS.SpatialFieldGradient

Geometry
South Facing Walls Without ProjectLocation
""
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DirectionCalculation\CS\bin\Debug\DirectionCalculation.dll
Revit.Samples.DirectionCalculation.FindSouthFacingWallsWithoutProjectLocation

Geometry
South Facing Walls With ProjectLocation
""
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DirectionCalculation\CS\bin\Debug\DirectionCalculation.dll
Revit.Samples.DirectionCalculation.FindSouthFacingWallsWithProjectLocation

Geometry
South Facing Windows Without ProjectLocation
""
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DirectionCalculation\CS\bin\Debug\DirectionCalculation.dll
Revit.Samples.DirectionCalculation.FindSouthFacingWindowsWithoutProjectLocation

Geometry
South Facing Windows With ProjectLocation
""
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DirectionCalculation\CS\bin\Debug\DirectionCalculation.dll
Revit.Samples.DirectionCalculation.FindSouthFacingWindowsWithProjectLocation

Geometry
Auto Join
Automatically join geometry of combinable elements.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FamilyCreation\AutoJoin\CS\bin\Debug\AutoJoin.dll
Ara3D.RevitSampleBrowser.AutoJoin.CS.Command

Geometry
Find Columns Embedded In Walls
Find Columns Embedded In Walls
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FindReferencesByDirection\FindColumns\CS\bin\Debug\FindColumns.dll
Ara3D.RevitSampleBrowser.FindColumns.CS.Command

Geometry
Measure Height of Skylight
Measure Height of Skylight
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FindReferencesByDirection\MeasureHeight\CS\bin\Debug\MeasureHeight.dll
Ara3D.RevitSampleBrowser.MeasureHeight.CS.Command

Geometry
RayTraceBounce
Find intersection between ray and face and create connecting lines.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FindReferencesByDirection\RaytraceBounce\CS\bin\Debug\RayTraceBounce.dll
Ara3D.RevitSampleBrowser.RayTraceBounce.CS.Command

Geometry
ComputedSymbolGeometry
Demonstrates how to get the computed symbol geometry.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\GeometryAPI\ComputedSymbolGeometry\CS\bin\Debug\ComputedSymbolGeometry.dll
Ara3D.RevitSampleBrowser.ComputedSymbolGeometry.CS.Command

Geometry
GeometryCreation_BooleanOperation
GeometryCreation and BooleanOperation
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\GeometryAPI\GeometryCreation_BooleanOperation\CS\bin\Debug\GeometryCreation_BooleanOperation.dll
Ara3D.RevitSampleBrowser.GeometryCreation_BooleanOperation.CS.Command

Geometry
Proximity Detection and Wall Join Control
The usage of  ElementIntersectsSolidFilter,ElementIntersectsElementFilter and WallUtils
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\GeometryAPI\ProximityDetection_WallJoinControl\CS\bin\Debug\ProximityDetection_WallJoinControl.dll
Ara3D.RevitSampleBrowser.ProximityDetection_WallJoinControl.CS.Command

Geometry
Compute distance to panels
Compute the distance from a selected object to all panels and store in a panel instance parameter
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\DistanceToPanels\CS\bin\Debug\DistanceToPanels.dll
Ara3D.RevitSampleBrowser.DistanceToPanels.CS.SetDistanceParam

Geometry
Manipulate form
Show how to manipulate edges and profiles of form
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\ManipulateForm\CS\bin\Debug\ManipulateForm.dll
Ara3D.RevitSampleBrowser.ManipulateForm.CS.Command

Geometry
Measure Panel Area
Measure curtain panels on divided surfaces and identify panels beyond a user-specified range
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\MeasurePanelArea\CS\bin\Debug\MeasurePanelArea.dll
Ara3D.RevitSampleBrowser.MeasurePanelArea.CS.MeasurePanelArea

Geometry
Compute the length and angle of edges
Measure curtain panels on divided surfaces, store the length and angle data to parameters
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\PanelEdgeLengthAngle\CS\bin\Debug\PanelEdgeLengthAngle.dll
Ara3D.RevitSampleBrowser.PanelEdgeLengthAngle.CS.SetLengthAngleParams

Geometry
Points Along Parabola
Points Along Parabola
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\PointCurveCreation\CS\bin\Debug\PointCurveCreation.dll
Ara3D.RevitSampleBrowser.PointCurveCreation.CS.PointsParabola

Geometry
Points On Curve
Points On Curve
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\PointCurveCreation\CS\bin\Debug\PointCurveCreation.dll
Ara3D.RevitSampleBrowser.PointCurveCreation.CS.PointsOnCurve

Geometry
Points From Text File
Points From Text File
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\PointCurveCreation\CS\bin\Debug\PointCurveCreation.dll
Ara3D.RevitSampleBrowser.PointCurveCreation.CS.PointsFromTextFile

Geometry
Curve - Sine
Curve - Sine
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\PointCurveCreation\CS\bin\Debug\PointCurveCreation.dll
Ara3D.RevitSampleBrowser.PointCurveCreation.CS.SineCurve

Geometry
Curve - Catenary
Curve - Catenary
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\PointCurveCreation\CS\bin\Debug\PointCurveCreation.dll
Ara3D.RevitSampleBrowser.PointCurveCreation.CS.CatenaryCurve

Geometry
Surface - Cyclic
Surface - Cyclic
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\PointCurveCreation\CS\bin\Debug\PointCurveCreation.dll
Ara3D.RevitSampleBrowser.PointCurveCreation.CS.CyclicSurface

Geometry
Material Quantities
Material Quantities
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\MaterialQuantities\CS\bin\Debug\MaterialQuantities.dll
Revit.Samples.MaterialQuantities.Command

Geometry
AddPredefinedInstance - Point Cloud Engine
Add predefined instance
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PointCloudEngine\CS\bin\Debug\PointCloudEngine.dll
Ara3D.RevitSampleBrowser.CS.PointCloudEngine.AddPredefinedInstanceCommand

Geometry
Add randomized instance - Point Cloud Engine
Add randomized instance
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PointCloudEngine\CS\bin\Debug\PointCloudEngine.dll
Ara3D.RevitSampleBrowser.CS.PointCloudEngine.AddRandomizedInstanceCommand

Geometry
Add randomized instance at transform - Point Cloud Engine
Add randomized instance at transform
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PointCloudEngine\CS\bin\Debug\PointCloudEngine.dll
Ara3D.RevitSampleBrowser.CS.PointCloudEngine.AddTransformedInstanceCommand

Geometry
Serialize point cloud (utility) - Point Cloud Engine
Serialize point cloud (utility)
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PointCloudEngine\CS\bin\Debug\PointCloudEngine.dll
Ara3D.RevitSampleBrowser.CS.PointCloudEngine.SerializePredefinedPointCloud

Geometry
SolidSolidCut-Cut
"Let the sphere cut the cube"
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SolidSolidCut\CS\bin\Debug\SolidSolidCut.dll
Ara3D.RevitSampleBrowser.SolidSolidCut.CS.Cut

Geometry
SolidSolidCut-Uncut
"Remove the cutting relationship between the sphere and the cube"
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SolidSolidCut\CS\bin\Debug\SolidSolidCut.dll
Ara3D.RevitSampleBrowser.SolidSolidCut.CS.Uncut

Geometry
Analytical Viewer
Display analytical model of one or more selected elements.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Viewers\AnalyticalViewer\VB.NET\bin\AnalyticalViewer.dll
Ara3D.RevitSampleBrowser.AnalyticalViewer.VB.NET.AnalyticalViewer

Geometry
Element Viewer
Display wireframe model of one or more selected elements.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Viewers\ElementViewer\VB.NET\bin\Debug\ElementViewer.dll
Ara3D.RevitSampleBrowser.ElementViewer.VB.NET.ElementViewer

Geometry
Revit Viewer
View geometry information.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Viewers\RevitViewer\VB.NET\bin\RevitViewer.dll
Ara3D.RevitSampleBrowser.RevitViewer.VB.NET.RevitViewer

Geometry
Room Viewer
Wireframe viewer for the selected room.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Viewers\RoomViewer\VB.NET\bin\RoomViewer.dll
Ara3D.RevitSampleBrowser.RoomViewer.VB.NET.RoomViewer

Geometry, Structure
NewPathReinforcement
Create PathReinforcement on wall or slab.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\NewPathReinforcement\CS\bin\Debug\NewPathReinforcement.dll
Ara3D.RevitSampleBrowser.NewPathReinforcement.CS.Command

Geometry, Structure
Truss
Create truss, edit profile and truss member of new created truss.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Truss\CS\bin\Debug\Truss.dll
Ara3D.RevitSampleBrowser.Truss.CS.Command

Massing
Set Parameter Values From Image Data
Set Parameter Values From Image Data
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\ParameterValuesFromImage\CS\bin\Debug\ParameterValuesFromImage.dll
Ara3D.RevitSampleBrowser.ParameterValuesFromImage.CS.SetParameterValueWithImageData

Materials
Edit appearance asset properties via a small control dialog
This sample demonstrates basic usage of the AppearanceAssetEditScope and AssetProperty classes to change the value of an asset property in a given material. 
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\AppearanceAssetEditing\CS\bin\Debug\AppearanceAssetEditing.dll
Ara3D.RevitSampleBrowser.AppearanceAssetEditing.CS.Command

Materials
Material Properties (CS)
Get the material physical properties of the selected beam, column or brace.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\MaterialProperties\CS\bin\Debug\MaterialProperties.dll
Ara3D.RevitSampleBrowser.MaterialProperties.CS.MaterialProperties

Materials, Parameters
Physical Properties
Dump Material Physical Parameters.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PhysicalProp\CS\bin\Debug\PhysicalProp.dll
Ara3D.RevitSampleBrowser.PhysicalProp.CS.DumpMaterialPhysicalParameters

MEP
AutoRoute
Route ducts and fittings.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\AutoRoute\CS\bin\Debug\AutoRoute.dll
Ara3D.RevitSampleBrowser.AutoRoute.CS.Command

MEP
AvoidObstruction
Resolve the obstructions of pipe with pipe, pipe with beam and pipe with duct.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\AvoidObstruction\CS\bin\Debug\AvoidObstruction.dll
Ara3D.RevitSampleBrowser.AvoidObstruction.CS.Command

MEP
Fabrication Part Layout
Fabrication Part Layout Sample
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.FabricationPartLayout

MEP
Optimize Straights
Optimize Straights
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.OptimizeStraights

MEP
Stretch and Fit
Stretch and fit
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.StretchAndFit

MEP
Convert To Fabrication
Convert Design Elements To Fabrication Parts
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.ConvertToFabrication

MEP
Buttons and Palette Exclusions
Exclude Fabrication Service Buttons and Palettes for Routing Operations
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.ButtonPaletteExclusions

MEP
Ancillaries
Discover the Ancillaries Associated with a Fabrication Part
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.Ancillaries

MEP
Get Custom Data
Discover the Custom data Associated with a Fabrication Config and Part
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.GetCustomData

MEP
Set Custom Data
Set Custom data Associated with a Fabrication Config to a Selected Part
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.SetCustomData

MEP
Export to PCF
Exports fabrication parts to a PCF file
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.ExportToPCF

MEP
Export Part Geometry
Exports fabrication part geometry to a CSV file
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.FabPartGeometry

MEP
Display Part Info
Displays fabrication part information
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.PartInfo

MEP
Detach Hanger Rods
Detaches hanger rods from their structural host
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.DetachRods

MEP
Double Rod Lengths
Doubles the length of the picked hanger rods
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.DoubleRodLength

MEP
Halve Rod Lengths
Halves the length of the picked hanger rods
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.HalveRodLength

MEP
Increase Rod Structure Extension
Increase the length of the rod as an extension from its hosted structure (by 1ft)
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.IncreaseRodStructureExtension

MEP
Decrease Rod Structure Extension
Decrease the length of the rod as an extension from its hosted structure (by 1ft)
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.DecreaseRodStructureExtension

MEP
Part Renumber
Renumbers a selection of fabrication parts
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.PartRenumber

MEP
Split Straight
Splits a fabrication part straight into two equal pieces
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.SplitStraight

MEP
Load and Place Next Item File
Reloads the fabrication configuration and then iterates the item folders and finds the next unloaded item file and lets a user place it in the model
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.LoadAndPlaceNextItemFile

MEP
Unload Unused Item Files
Unloads item files that are loaded but are not used in the model
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.UnloadUnusedItemFiles

MEP
Export to MAJ
Export Fabrication Parts to a fabrication job (MAJ) file
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.ExportToMAJ

MEP
Change Service
Change the service of a selection of Fabrication Parts
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.ChangeService

MEP
Change Size
Change the size of a selection of Fabrication Parts
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.ChangeSize

MEP
Apply Change
Apply change to the service and the size of a selection of Fabrication Parts
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.ApplyChange

MEP
Flip Part
Flips a Fabrication Part to the opposite direction
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\FabricationPartLayout.dll
Ara3D.RevitSampleBrowser.FabricationPartLayout.CS.FlipPart

MEP
Pressure Loss Report
Report the pressure loss for the network flow calculation.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\NetworkPressureLossReport\CS\bin\Debug\NetworkPressureLossReport.dll
Ara3D.RevitSampleBrowser.NetworkPressureLossReport.Command

MEP
Power Circuit
Operate power circuits.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PowerCircuit\CS\bin\Debug\PowerCircuit.dll
Ara3D.RevitSampleBrowser.PowerCircuit.CS.Command

MEP
RoutingPreferenceTools.Analyzer
RoutingPreferenceTools.Analyzer
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RoutingPreferenceTools\CS\bin\Debug\RoutingPreferenceTools.dll
Ara3D.RevitSampleBrowser.RoutingPreferenceTools.CS.Command

MEP
RoutingPreferenceTools.Builder.CommandReadPreferences
RoutingPreferenceTools.Builder.CommandReadPreferences
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RoutingPreferenceTools\CS\bin\Debug\RoutingPreferenceTools.dll
Ara3D.RevitSampleBrowser.RoutingPreferenceTools.CS.CommandReadPreferences

MEP
RoutingPreferenceTools.Builder.CommandWritePreferences
RoutingPreferenceTools.Builder.CommandWritePreferences
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RoutingPreferenceTools\CS\bin\Debug\RoutingPreferenceTools.dll
Ara3D.RevitSampleBrowser.RoutingPreferenceTools.CS.CommandWritePreferences

MEP
TraverseSystem
Traverse a mechanical or piping system in the direction of flow
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\TraverseSystem\CS\bin\Debug\TraverseSystem.dll
Ara3D.RevitSampleBrowser.TraverseSystem.CS.Command

Parameters
Beam and slab parameter
Add a new GUID parameter to beam and slab, and use the GUID value to find the right element.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\BeamAndSlabNewParameter\CS\bin\Debug\BeamAndSlabNewParameter.dll
Ara3D.RevitSampleBrowser.BeamAndSlabNewParameter.CS.Command

Parameters
Browse Parameter Bindings
Browse all the shared parameters bindings used in this project.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\BrowseBindings\VB.NET\bin\BrowseBindings.dll
Ara3D.RevitSampleBrowser.BrowseBindings.VB.NET.Command

Parameters
CreateShared - Create Shared Parameter
Create a new shared parameter and assign it to wall categories.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateShared\VB.NET\bin\Debug\CreateShared.dll
Ara3D.RevitSampleBrowser.CreateShared.VB.NET.Command1

Parameters
CreateShared - Set Shared Parameter
Set the shared parameter.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateShared\VB.NET\bin\Debug\CreateShared.dll
Ara3D.RevitSampleBrowser.CreateShared.VB.NET.Command2

Parameters
Get Deck Properties
Get deck layer properties.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DeckProperties\CS\bin\Debug\DeckProperties.dll
Ara3D.RevitSampleBrowser.DeckProperties.CS.Command

Parameters
FireRating - Apply Parameter
Add a new shared parameter to Revit and apply it to all doors.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FireRating\VB.NET\bin\FireRating.dll
Ara3D.RevitSampleBrowser.FireRating.VB.NET.ApplyParameter

Parameters
FireRating - Export to Excel
Export fire rating values to an Excel file.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FireRating\VB.NET\bin\FireRating.dll
Ara3D.RevitSampleBrowser.FireRating.VB.NET.ExportFireRating

Parameters
FireRating - Import from Excel
Import fire rating values from the Excel file and apply them to doors.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FireRating\VB.NET\bin\FireRating.dll
Ara3D.RevitSampleBrowser.FireRating.VB.NET.ImportFireRating

Parameters
Create shared parameters
Create a visible and an invisible parameter.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\InvisibleParam\CS\bin\Debug\InvisibleParam.dll
Ara3D.RevitSampleBrowser.InvisibleParam.CS.Command

Parameters
Element Parameters
Show the property information of selected element.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ParameterUtils\CS\bin\Debug\ParameterUtils.dll
Ara3D.RevitSampleBrowser.ParameterUtils.CS.Command

Parameters
ReadonlySharedParameters1
ReadonlySharedParameters1
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ReadonlySharedParameters\CS\bin\Debug\ReadonlySharedParameters.dll
Ara3D.RevitSampleBrowser.ReadonlySharedParameters.CS.SetReadonlyCost1

Parameters
ReadonlySharedParameters2
ReadonlySharedParameters2
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ReadonlySharedParameters\CS\bin\Debug\ReadonlySharedParameters.dll
Ara3D.RevitSampleBrowser.ReadonlySharedParameters.CS.SetReadonlyCost2

Parameters
Test Floor Thickness
Show how to retrieve and modify floor thickness.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\TestFloorThickness\VB.NET\bin\Debug\TestFloorThickness.dll
Ara3D.RevitSampleBrowser.TestFloorThickness.VB.NET.Command

Parameters
Test Wall Thickness
Show how to retrieve and modify wall thickness.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\TestWallThickness\VB.NET\bin\Debug\TestWallThickness.dll
Ara3D.RevitSampleBrowser.TestWallThickness.VB.NET.Command

Parameters, Structure
Create beams, columns and braces (CS)
Create beams, columns and braces.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateBeamsColumnsBraces\CS\bin\Debug\CreateBeamsColumnsBraces.dll
Ara3D.RevitSampleBrowser.CreateBeamsColumnsBraces.CS.Command

Parameters, Views
Create and configure new view template
Demonstrates the process of creating a new view template from a regular view.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ViewTemplateCreation\CS\bin\Debug\ViewTemplateCreation.dll
Ara3D.RevitSampleBrowser.ViewTemplateCreation.CS.Command

Rooms/Spaces
Create zone and space
Create space/zone elements and edit zone in Revit MEP.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\AddSpaceAndZone\CS\bin\Debug\AddSpaceAndZone.dll
Ara3D.RevitSampleBrowser.AddSpaceAndZone.CS.Command

Rooms/Spaces
Customize door opening expression
Customize door opening expression based on geometry and your country standard.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DoorSwing\CS\bin\Debug\DoorSwing.dll
Ara3D.RevitSampleBrowser.DoorSwing.CS.InitializeCommand

Rooms/Spaces
Update Door Properties
Update Door Properties according to geometries.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DoorSwing\CS\bin\Debug\DoorSwing.dll
Ara3D.RevitSampleBrowser.DoorSwing.CS.UpdateParamsCommand

Rooms/Spaces
Update Door Geometries
Update door geometry according to From/To room property.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DoorSwing\CS\bin\Debug\DoorSwing.dll
Ara3D.RevitSampleBrowser.DoorSwing.CS.UpdateGeometryCommand

Rooms/Spaces
Roofs Rooms (CS)
Demonstrates how to check whether Room(Space) has bounding Roof.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RoofsRooms\CS\bin\Debug\RoofsRooms.dll
Ara3D.RevitSampleBrowser.RoofsRooms.CS.Command

Rooms/Spaces
Rooms
Get and set room information (Number, Tag, Area).
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Rooms\CS\bin\Debug\Rooms.dll
Ara3D.RevitSampleBrowser.Rooms.CS.Command

Rooms/Spaces
Room Schedule
Room Schedule.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RoomSchedule\CS\bin\Debug\RoomSchedule.dll
Ara3D.RevitSampleBrowser.RoomSchedule.Command

Selection
Pick for Deletion
This command is to pick element and delete.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Selections\CS\bin\Debug\Selections.dll
Ara3D.RevitSampleBrowser.Selections.CS.PickforDeletion

Selection
Place At Point On Wall Face
This command is to pick a point on wall face and place a window.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Selections\CS\bin\Debug\Selections.dll
Ara3D.RevitSampleBrowser.Selections.CS.PlaceAtPointOnWallFace

Selection
Place At Picked Face Work plane
This command is to pick a face, set work plane, then pick a point to create a circle.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Selections\CS\bin\Debug\Selections.dll
Ara3D.RevitSampleBrowser.Selections.CS.PlaceAtPickedFaceWorkplane

Selection
Selection Dialog
This command is to pick a element and a point from dialog.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Selections\CS\bin\Debug\Selections.dll
Ara3D.RevitSampleBrowser.Selections.CS.SelectionDialog

Structure
Analytical SupportData Information
Displays the element's support information
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\AnalyticalSupportData_Info\CS\bin\Debug\AnalyticalSupportData_Info.dll
Ara3D.RevitSampleBrowser.AnalyticalSupportData_Info.CS.Command

Structure
AreaReinCurve
Turn off all layers but one. You get some parallel bars. Remove the hooks from one boundary curve so that the bars have hooks only at the other end.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\AreaReinCurve\CS\bin\Debug\AreaReinCurve.dll
Ara3D.RevitSampleBrowser.AreaReinCurve.CS.Command

Structure
AreaReinParameters
Show parameters of selected AreaReinforcement and allow user to modify
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\AreaReinParameters\CS\bin\Debug\AreaReinParameters.dll
Ara3D.RevitSampleBrowser.AreaReinParameters.CS.Command

Rebar
RebarParameters
Show all parameters of selected Rebar
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\AreaReinParameters\CS\bin\Debug\AreaReinParameters.dll
Ara3D.RevitSampleBrowser.AreaReinParameters.CS.RebarParas

Structure
Boundary Conditions
Display the BoundaryConditions' parameters or create a new BoundaryConditions instance.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\BoundaryConditions\CS\bin\Debug\BoundaryConditions.dll
Ara3D.RevitSampleBrowser.BoundaryConditions.CS.Command

Structure
Create Beam System
Create beam system according to the profile made of selected beams.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateBeamSystem\CS\bin\Debug\CreateBeamSystem.dll
Ara3D.RevitSampleBrowser.CreateBeamSystem.CS.Command

Structure
Create Complex Area Reinforcement
Create complex AreaReinforcement on selected slab.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateComplexAreaRein\CS\bin\Debug\CreateComplexAreaRein.dll
Ara3D.RevitSampleBrowser.CreateComplexAreaRein.CS.Command

Structure
Create simple area reinforcement
Create simple AreaReinforcement on selected wall or floor.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateSimpleAreaRein\CS\bin\Debug\CreateSimpleAreaRein.dll
Ara3D.RevitSampleBrowser.CreateSimpleAreaRein.CS.Command

Structure
Create wall in beam profile
Create a profiled wall using the outline generated by a selection of beams defining a vertical profile.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateWallinBeamProfile\CS\bin\Debug\CreateWallinBeamProfile.dll
Ara3D.RevitSampleBrowser.CreateWallinBeamProfile.CS.CreateWallinBeamProfile

Structure
Create walls under beams
Create simple rectangular walls along and under the path of selected beams.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateWallsUnderBeams\CS\bin\Debug\CreateWallsUnderBeams.dll
Ara3D.RevitSampleBrowser.CreateWallsUnderBeams.CS.CreateWallsUnderBeams

Structure
Create Curved Beam
Create Curved Beam.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CurvedBeam\CS\bin\Debug\CurvedBeam.dll
Ara3D.RevitSampleBrowser.CurvedBeam.CS.Command

Structure
Frame Builder
Add a new concrete column and beam size.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FrameBuilder\CS\bin\Debug\FrameBuilder.dll
Ara3D.RevitSampleBrowser.FrameBuilder.CS.Command

Structure
Structural connection basic operations
Shows how to perform basic operations on a structural connection.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\GenericStructuralConnection\CS\bin\Debug\GenericStructuralConnection.dll
Ara3D.RevitSampleBrowser.GenericStructuralConnection.CS.Command

Structure
Loads
Show how to use load case, nature, usage and combination.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Loads\CS\bin\Debug\Loads.dll
Ara3D.RevitSampleBrowser.Loads.CS.Loads

Rebar
Multiplanar Rebar
Demonstrates how to create multiplanar rebar.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\MultiplanarRebar\CS\bin\Debug\MultiplanarRebar.dll
Ara3D.RevitSampleBrowser.MultiplanarRebar.CS.Command

Rebar
NewRebar
Create a rebar on the selected concrete rectangular column or beam.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\NewRebar\CS\bin\Debug\NewRebar.dll
Ara3D.RevitSampleBrowser.NewRebar.CS.Command

Rebar
PathReinforcement
Display path reinforcement properties.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PathReinforcement\CS\bin\Debug\PathReinforcement.dll
Ara3D.RevitSampleBrowser.PathReinforcement.CS.Command

Rebar
RebarContainerAnyShapeType
Create Rebar Container in a selected concrete element (beam or column) that does not have any reinforcement.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RebarContainerAnyShapeType\CS\bin\Debug\RebarContainerAnyShapeType.dll
Ara3D.RevitSampleBrowser.RebarContainerAnyShapeType.CS.Command

Rebar
Add Parameters
External command to add shared parameters to Rebar
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RebarFreeForm\CS\bin\Debug\RebarFreeForm.dll
Ara3D.RevitSampleBrowser.RebarFreeForm.CS.AddSharedParams

Rebar
Create Rebar Free Form
External command to create a Rebar FreeForm element and external application to implement the custom server used to regenerate the rebar geometry based on constraints
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RebarFreeForm\CS\bin\Debug\RebarFreeForm.dll
Ara3D.RevitSampleBrowser.RebarFreeForm.CS.Command

Structure
Reinforcement
Create bar set in a selected concrete element (beam or column) that does not have any reinforcement.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Reinforcement\CS\bin\Debug\Reinforcement.dll
Ara3D.RevitSampleBrowser.Reinforcement.CS.Command

Structure
Add elements to connection
Add elements to existing structural connection
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\SampleCommandsSteelElements.dll
Ara3D.RevitSampleBrowser.SampleCommandsSteelElements.AddElementsToConnection.CS.Command

Structure
Add elements to custom connection
Add elements to existing custom connection
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\SampleCommandsSteelElements.dll
Ara3D.RevitSampleBrowser.SampleCommandsSteelElements.AddElementsToCustomConnection.CS.Command

Structure
Add ranges of applicability to a connection type
Add ranges of applicability to a connection type
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\SampleCommandsSteelElements.dll
Ara3D.RevitSampleBrowser.SampleCommandsSteelElements.AddRangesToConnectionType.CS.Command

Structure
Create anchor pattern
Create anchor pattern
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\SampleCommandsSteelElements.dll
Ara3D.RevitSampleBrowser.SampleCommandsSteelElements.CreateAnchorPattern.CS.Command

Structure
Create bolt pattern
Create bolt pattern
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\SampleCommandsSteelElements.dll
Ara3D.RevitSampleBrowser.SampleCommandsSteelElements.CreateBoltPattern.CS.Command

Structure
Create contour cut
Create contour cut
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\SampleCommandsSteelElements.dll
Ara3D.RevitSampleBrowser.SampleCommandsSteelElements.CreateContourCut.CS.Command

Structure
Create cope skewed
Create cope skewed
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\SampleCommandsSteelElements.dll
Ara3D.RevitSampleBrowser.SampleCommandsSteelElements.CreateCopeSkewed.CS.Command

Structure
Create corner cut
Create corner cut
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\SampleCommandsSteelElements.dll
Ara3D.RevitSampleBrowser.SampleCommandsSteelElements.CreateCornerCut.CS.Command

Structure
Create plate
Create plate
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\SampleCommandsSteelElements.dll
Ara3D.RevitSampleBrowser.SampleCommandsSteelElements.CreatePlate.CS.Command

Structure
Create plate hole
Create plate hole
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\SampleCommandsSteelElements.dll
Ara3D.RevitSampleBrowser.SampleCommandsSteelElements.CreatePlateHole.CS.Command

Structure
Create shear stud pattern
Create shear stud pattern
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\SampleCommandsSteelElements.dll
Ara3D.RevitSampleBrowser.SampleCommandsSteelElements.CreateShearStudPattern.CS.Command

Structure
Create shortening
Create shortening
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\SampleCommandsSteelElements.dll
Ara3D.RevitSampleBrowser.SampleCommandsSteelElements.CreateShortening.CS.Command

Structure
Create weld point
Create weld point
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\SampleCommandsSteelElements.dll
Ara3D.RevitSampleBrowser.SampleCommandsSteelElements.CreateWeldPoint.CS.Command

Structure
Delete connection
Delete connection
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\SampleCommandsSteelElements.dll
Ara3D.RevitSampleBrowser.SampleCommandsSteelElements.DeleteConnection.CS.Command

Structure
Remove elements from structural connection
Remove elements from structural connection
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\SampleCommandsSteelElements.dll
Ara3D.RevitSampleBrowser.SampleCommandsSteelElements.RemoveElementsFromConnection.CS.Command

Structure
Remove subelements from custom connection
Remove subelements from custom connection
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\SampleCommandsSteelElements.dll
Ara3D.RevitSampleBrowser.SampleCommandsSteelElements.RemoveSubelementsFromCustomConnection.CS.Command

Structure
Print connection detailed parameters
Print connection detailed parameters
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\SampleCommandsSteelElements.dll
Ara3D.RevitSampleBrowser.SampleCommandsSteelElements.UpdateConnectionDetailedParameters.CS.Command

Structure
Fabrication transaction and background calculation
Shows how to handle "Background calculation in progress" exception when trying to start fabrication transaction
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\SampleCommandsSteelElements.dll
Ara3D.RevitSampleBrowser.SampleCommandsSteelElements.BackgroundCalculation.CS.Command

Structure
StructSample - Frame Wall
Add columns to the selected walls.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\StructSample\CS\bin\Debug\StructSample.dll
Ara3D.RevitSampleBrowser.StructSample.CS.Command

Structure
Structural Layer Function (CS)
For the selected floor, display the function of each structural layer from outside to inside in a dialog box.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\StructuralLayerFunction\CS\bin\Debug\StructuralLayerFunction.dll
Ara3D.RevitSampleBrowser.StructuralLayerFunction.CS.Command

View Transforms
Sheet To 3D View
Generate a perspective View3D with its camera at a click on a viewport on a sheet
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SheetToView3D\CS\bin\Debug\SheetToView3D.dll
Ara3D.RevitSampleBrowser.SheetToView3D.CS.Command

Views
All Views
Generate a new sheet for user selected views
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\AllViews\CS\bin\Debug\AllViews.dll
Ara3D.RevitSampleBrowser.AllViews.CS.Command

Views
Create view section
Create a section view across the mid point of the selected wall, floor or beam
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateViewSection\CS\bin\Debug\CreateViewSection.dll
Ara3D.RevitSampleBrowser.CreateViewSection.CS.Command

Views
Create drafting view
Create a new empty drafting view
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateViewSection\CS\bin\Debug\CreateViewSection.dll
Ara3D.RevitSampleBrowser.CreateViewSection.CS.CreateDraftingView

Views
Object Viewer
Display the selected element in a preview window and generic properties in a grid.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ObjectViewer\CS\bin\Debug\ObjectViewer.dll
Ara3D.RevitSampleBrowser.ObjectViewer.CS.Command

Views
ScheduleAPI
This sample introduces how to create a view schedule and how to show its data on a sheet.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ScheduleCreation\CS\bin\Debug\ScheduleCreation.dll
Ara3D.RevitSampleBrowser.ScheduleCreation.CS.Command

Views
Visibility Controller
Control element visibility by category.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\VisibilityControl\CS\bin\Debug\VisibilityControl.dll
Ara3D.RevitSampleBrowser.VisibilityControl.CS.Command

